openapi: 3.0.2
info:
  title: 'GA4GH Service API Specification'
  version: 1.0.0
  description: 'More information on [GitHub](https://github.com/mcupak/ga4gh-specification-template).'
  license:
    name: 'Apache 2.0'
    url: 'https://raw.githubusercontent.com/mcupak/ga4gh-specification-template/develop/LICENSE'
  contact:
    name: 'Foo Bar'
    email: 'foobar@example.com'
security:
  - bearerAuth: []
paths:
  /service-info:
    # Links to the latest version of service-info. Use a tag once service-info is released instead.
    $ref: 'https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-service-info/develop/service-info.yaml#/paths/~1service-info'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT